site_name: Multi-Modal Molecular Analyses for Living Drugs
use_directory_urls: true
docs_dir: wiki

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      toc_depth: 2

nav:
  - Technologies:
      - Home/Technologies/index.md
  - Pipelines:
      - Home/Pipelines/index.md
      - LivingDrugOmics:
          - Home/Pipelines/LivingDrugOmics-Pipeline/index.md
          - Documentation:
              - Params File: Home/Pipelines/LivingDrugOmics-Pipeline/Documentation/params-file.md
              - Reference building: Home/Pipelines/LivingDrugOmics-Pipeline/Documentation/reference_building.md
              - Command Line Arguments: Home/Pipelines/LivingDrugOmics-Pipeline/Documentation/cli.md
              - Output: Home/Pipelines/LivingDrugOmics-Pipeline/Documentation/output.md
  - Resources:
      - Home/Resources/index.md
      - CAR Constructs: Home/Resources/CAR-constructs.md
      - Vector Systems: Home/Resources/Vector-systems.md

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.integrate
  logo: images/Logo_light.png

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fraunhofer-izi
  generator: false